### ISSUE TITLE
NullPointerException in getItemCount()

### ISSUE THREAD

**Issue by mybirthfather** [afollestad/drag-select-recyclerview#29]
I am sorry。 I think the auther is a Chinese。And My English is Too bad. So I describe My issue Simply。

Use this DragSelectRecyclerView when I try to repeat the click into a Fragment when the use of this fragment in the view, will be reported in the DragSelectRecyclerView this place will be  nullpointerexception.
```java
@Override
     Public boolean dispatchTouchEvent (MotionEvent e) {
         If (mAdapter.getItemCount () == 0)
             Return super.dispatchTouchEvent (e);
```
Error pointing to this place, error mAdapter.getItemCount () is nullpointerexception. I tried to inherit DragSelectRecyclerView he rewrite this method to judge the mAdapter! = Null; the results of the last call to the father of this method, or a null pointer. So no way I put the author of the code all copy again, plus a judge. Hey, and finally thank the author. This library is used to select multiple items in the project. Thanks again

**Comment by vitovalov** [comment]
Any news on this crash? 
I'm seeing crash reports but the app is big and the stacktrace isn't helpful because gives no context when it happens. 

I think it's because the adapter was not yet created and the list had the listener already attached. 


`com.afollestad.dragselectrecyclerview.DragSelectRecyclerView.dispatchTouchEvent (DragSelectRecyclerView.java:221)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2343)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:1991)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2343)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:1991)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2343)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:1991)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2343)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:1991)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2343)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:1991)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2343)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:1991)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2343)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:1991)
com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent (PhoneWindow.java:2146)
com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1578)
android.app.Activity.dispatchTouchEvent (Activity.java:2505)
android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:71)
android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:71)
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent (PhoneWindow.java:2094)
android.view.View.dispatchPointerEvent (View.java:8010)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:4576)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4447)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3993)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4043)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4012)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4119)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4020)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4176)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3993)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4043)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4012)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4020)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3993)
android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:6275)
android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:6237)
android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6191)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:6423)
android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:140)
android.os.Looper.loop (Looper.java:150)
android.app.ActivityThread.main (ActivityThread.java:5322)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:829)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:645)
dalvik.system.NativeStart.main (NativeStart.java)`

**Comment by afollestad** [comment]
https://github.com/afollestad/drag-select-recyclerview/releases/tag/2.0.0
