### ISSUE TITLE
Drag selection remains active after ACTION_UP when ACTION_MOVE is not called

### ISSUE THREAD

**Issue by Sdghasemi** [afollestad/drag-select-recyclerview#34]
- Library version: `2.3.0`
 - Device OS version: Any version
 - Device Manufacturer: No difference
 - Device Name: Whatever

 
###### Reproduction Steps
1.  Easier to use an emulator to test so that the mouse pointer does not move at all than a real device with finger touch.
2. Run emulator with the sample app running
3. Long press on an item and the release it after the selection start began whilst you're not moving the mouse
4. Try to scroll the list normally

###### Expected Result
Drag selection should be deactivated after you have released your touch and pressing and moving should scroll the list afterwards.

###### Actual Result
It continues to select items considering the clicked item as the starting point which is really annoying when you need to scroll the list.

Thanks for the library but I would appreciate it to fix this bug cause it affects even normal scrolling (happens occasionally)

**Comment by Sdghasemi** [comment]
Any possible updates?

**Comment by Carlosph** [comment]
I experienced the same problem.

**Expected behavior:**

<img src="https://user-images.githubusercontent.com/3061616/54585647-f4e89880-4a1a-11e9-9fa4-6dfb6ed4fd02.gif" height="420">

**Issue:**

<img src="https://user-images.githubusercontent.com/3061616/54585648-f5812f00-4a1a-11e9-9bdf-6edab096f35e.gif" height="420">

**The source of the issue:**

When the user long press on an item to start the drag selection, the method `onInterceptTouchEvent` does returns `false` for the `ACTION_DOWN` event. Therefore the next event wont be processed by `onTouchEvent`. Then the next events may be:

- Some `ACTION_MOVE` events followed by and `ACTION_UP`. In this case there is no problem because the first event is processed by `onInterceptTouchEvent` which returns `true` as `dragSelectActive` is true by then. And the following events are processed by `onTouchEvent`.

- A single `ACTION_UP` event. In this case is where the unexpected behavior is happening. The event is consumed by the method `onInterceptTouchEvent` and the logic to terminate the drag selection is only called from the method `onTouchEvent`.

**Proposed solution:**

When an `ACTION_UP` event is detected on the method `onInterceptTouchEvent`, and `dragSelectActive && !adapterIsEmpty` is `true` the drag selection must be ended.

**Comment by afollestad** [comment]
Thanks @Carlosph

**Comment by Carlosph** [comment]
Sure, thanks to you for the library!
