### ISSUE TITLE
Question: How do you refresh the grid after the underlying adapter is changed?

### ISSUE THREAD

**Issue by GeorgeChackungal** [afollestad/drag-select-recyclerview#5]
How do you refresh the grid after the underlying adapter is changed?

**Comment by eneim** [comment]
This is kind of interesting. Normally I would call notifyItem**/notifyDataSet** to ask the Adapter to update its grid. For now, I notice that you set the adapter position as viewholder's tag, and get that position in onClick/onLongClick (your [sample](https://github.com/afollestad/drag-select-recyclerview/blob/master/sample/src/main/java/com/afollestad/dragselectrecyclerviewsample/MainAdapter.java)). The fact that after calling ```Adapter#notifyItemRemove```, the adapter won't call onBindViewHolder again, the layout manager will take care of the UI change instead, so your viewholder's index might become incorrect and could throw an OutOfBoundException if you click to you item after you remove some of them.

Wait for your response.

**Comment by afollestad** [comment]
Well, the only way to do that is make a call to `notifyItemDataSetChanged()` unfortunately.

`notifyItemRemoved` and the other adapter update methods are final so I cannot override them.

**Comment by eneim** [comment]
There is something you could do, but they are more complicated: use adapterPosition and layoutPosition of a ViewHolder. As official document says: those 2 value are the same most of the time, except for the time of laying out ... I really want to use the sub method (notifyItem~~) because it would nicely support Item Animation. But yet it totally depends on your usage.

FYI, In my own implementation, I check the 2 above position, in case they match each other, it means that we have a stable view (RecyclerView finished its laying out process), which could accept touch/click event perfectly, that time I dispatch my own event.

**Comment by afollestad** [comment]
https://github.com/afollestad/drag-select-recyclerview/issues/6
